#!/bin/bash
set -e

device="${DEVICE?}"
base_dir="${BASE_DIR:-$PWD/base}"
build_type="${BUILD_TYPE:-release}"
build_variant="${BUILD_VARIANT:-user}"
build_datetime="${BUILD_DATETIME:-$(date --utc +%s)}"
build_number="${BUILD_NUMBER:-$(date --utc -d "@$build_datetime" +%m%d%H%M )}"
config_dir="${CONFIG_DIR:-/opt/android}"
key_dir=$( \
	[ "$build_variant" == "user" ] \
	&& echo "${KEY_DIR:-${PWD}/keys/${device}}/" \
	|| echo "${base_dir}/build/target/product/security/" \
)
key_hash=$( \
	openssl x509 -in "${key_dir}/platform.x509.pem" -outform DER \
	| sha256sum | cut -c 64; \
)
fdroid_org="packages/apps/F-DroidPrivilegedExtension/app/src/main/java/org"
fdroid_whitelist="${fdroid_org}/fdroid/fdroid/privileged/ClientWhitelist.java"
cores=$(nproc)
echo "Setting key directory to: $key_dir"
echo "Setting platform key hash to: $key_hash"

# Sync/reset repos
cd "${base_dir}"
repo init -u "${config_dir}" -m manifests/base.xml
repo sync -c --no-tags --no-clone-bundle --jobs "${cores}"
repo forall -c 'git reset --hard ; git clean -fdx'

# Apply Patches
for patch in "${config_dir}"/patches/*.patch; do
	patch -p1 --no-backup-if-mismatch < "${patch}"
done
echo "patching file ${fdroid_whitelist}"
sed -i "s/[a-f0-9]\{64\}/${key_hash}/g" "${base_dir}/${fdroid_whitelist}"

# Build Platform
# shellcheck disable=SC1091
source build/envsetup.sh
choosecombo "${build_type}" "aosp_${device}" "${build_variant}"
export LANG=C
export BUILD_NUMBER="$build_number"
export BUILD_DATETIME="$build_datetime"
make -j "${cores}" target-files-package brillo_update_payload
