#!/bin/bash

set -e
rm -rf "$HOME/.gradle"
rm -rf "$HOME/.android"
rm -rf "$HOME/.cache"
cd "$HOME/base" || exit
make clean
repo forall -c 'git reset --hard ; git clean -fdx'
mapfile -t -d '' dirs \
	< <(find "$HOME/external/kernel" -maxdepth 1 -mindepth 1 -type d -print0)
for dir in "${dirs[@]}"; do (
	cat <<-EOF | bash
		cd "$dir" || exit;
		repo forall -c 'git reset --hard ; git clean -fdx';
		rm -rf out
	EOF
) done
