#!/usr/bin/python3

from html.parser import HTMLParser
from urllib.request import urlopen
from os import environ
import json
import re
import os.path

class AndroidImagesParser(HTMLParser):

    def __init__(self, config):
        HTMLParser.__init__(self)
        self.config = config
        self.devices = self.config['devices'].keys()
        self.version = self.config['version']
        self.version_open = False
        self.hash_pattern = re.compile(r'\b[0-9a-f]{64}\b')
        self.images = {}
        self.image = {}
        self.build = False
        self.variant = False
        self.device = False

    def handle_starttag(self, tag, attrs):
        if tag == 'tr':
            for attr in attrs:
                if attr[0] == 'id':
                    for device in self.devices:
                        if attr[1].startswith(device):
                            self.image = {}
                            self.device = device

    def handle_data(self, data):
        if self.device:
            if len(data) > 6:
                if self.hash_pattern.match(data) \
                and self.version_open == True:
                    self.image['factory_hash'] = data
                elif data.split(' ')[0].startswith("%s." % self.version):
                    self.version_open = True
                    tokens = data.split(" ")
                    self.image['build'] = tokens[1].replace("(","").replace(",", "")
                    variant = tokens[4:5]
                    if variant:
                        self.variant = variant[0].replace(")","").lower()
                    else:
                        self.variant = "global"

    def handle_endtag(self, tag):
        if tag == 'tr' and self.device and self.variant:
            if self.version_open == True:
                self.images.setdefault(
                    self.device,{}
                )[self.variant] = self.image
                self.version_open = False
            self.device = False
            self.build = False
            self.variant = False

if __name__ == "__main__":

    if 'CONFIG_FILE' in environ:
        config_file=environ['CONFIG_FILE']
    elif os.path.isfile('/opt/android/config.json'):
        config_file="/opt/android/config.json"
    elif os.path.isfile('./config.json'):
        config_file="./config.json"
    with open(config_file, encoding='utf-8') as data_file:
        config = json.loads(data_file.read())

    url = "https://developers.google.com/android/images"
    html = urlopen(url).read()
    parser = AndroidImagesParser(config)
    parser.images = {}
    parser.feed(str(html))
    config['devices'] = parser.images

    print(json.dumps(config,indent=4))
