#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; eval "$(environment)"

cp /etc/gitconfig ~/.gitconfig

base_dir="${BASE_DIR?}"
manifest_dir="${MANIFEST_DIR?}"
manifest_work_tree="$HOME/.cache/manifests"
cores=$(nproc)

mkdir -p "${base_dir}" "${manifest_work_tree}"

rsync -Pav "${manifest_dir}/" "${manifest_work_tree}/"

[ -d "${manifest_work_tree}/.git" ] || {
	export GIT_WORK_TREE="$manifest_work_tree"
	export GIT_DIR="${manifest_work_tree}/.git"
	git init
	git add .
	git commit -a -m "automated cache commit"
}


cd "${base_dir}"

repo init -u "${manifest_work_tree}" -m base.xml

retry 3 repo sync -c --no-tags --no-clone-bundle --jobs "${cores}"

repo forall -c 'git reset --hard ; git clean -fdx'
