#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; eval "$(environment)";

cd "$HOME/base"

device="${DEVICE?}"
build_type="${BUILD_TYPE:-release}"
build_variant="${BUILD_VARIANT:-user}"

# shellcheck disable=SC1091
source build/envsetup.sh
choosecombo "${build_type}" "${device}" "${build_variant}"

fastboot devices
fastboot flashall -w
