#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
eval "$(environment)"
set -o nounset -o pipefail -o errexit

base_dir="${BASE_DIR?}"
key_dir="${KEY_DIR?}"

cd "${base_dir}"
fdroid_org="packages/apps/F-DroidPrivilegedExtension/app/src/main/java/org"
fdroid_whitelist="${fdroid_org}/fdroid/fdroid/privileged/ClientWhitelist.java"
platform_key_hash=$( \
	openssl x509 -in "${key_dir}/platform.x509.pem" -outform DER \
	| sha256sum | cut -c1-64; \
)
echo "Platform Key Hash: ${platform_key_hash}"
if [ -f "${base_dir}/${fdroid_whitelist}" ]; then
	echo "patching file ${fdroid_whitelist}"
	sed -i \
			"s/[a-f0-9]\\{64\\}/${platform_key_hash}/g" \
			"${base_dir}/${fdroid_whitelist}"
fi
