#!/bin/bash
# shellcheck disable=SC1091,SC1090
set -e

img_path() {
	image=${1?}
	path=${2?}
 	grep -Po \
 		"require version-${image}=\\K.+" \
 		"${path}/vendor-board-info.txt" \
 	| tr '[:upper:]' '[:lower:]'
}

device="${DEVICE?}"
base_dir="$PWD/base"
build_number="$(cat "${base_dir}"/out/build_number.txt 2>/dev/null)"
prefix=aosp_
target_files="${device}-target_files-${build_number}.zip"
key_dir="${KEY_DIR:-${PWD}/keys/${device}}"
release_dir="$PWD/release/${device}/${build_number}"
target_out_dir="${base_dir}/out/target/product/${device}"
inter_dir="${target_out_dir}/obj/PACKAGING/target_files_intermediates"
bootloader=$(img_path bootloader "${base_dir}/vendor/google_devices/${device}")
radio=$(img_path baseband "${base_dir}/vendor/google_devices/${device}")
version=$(
	grep -Po \
		"export BUILD_ID=\\K.+" \
		"${base_dir}/build/core/build_id.mk" \
	| tr '[:upper:]' '[:lower:]' \
)


export PATH="${base_dir}/build/tools/releasetools:$PATH"
export LANG=C
export _JAVA_OPTIONS=-XX:-UsePerfData
export BUILD_NUMBER="$build_number"

cd "$base_dir"
sudo mkdir -p "$release_dir"
sudo chown -R build:build "$release_dir"

echo "Running sign_target_files_apks"
sign_target_files_apks \
	-o \
	-d "$key_dir" \
	--avb_vbmeta_key "${key_dir}/avb.pem" \
    --avb_vbmeta_algorithm SHA256_RSA2048 \
    --avb_system_key "${key_dir}/avb.pem" \
    --avb_system_algorithm SHA256_RSA2048 \
  	"${inter_dir}/${prefix}${device}-target_files-${build_number}.zip" \
	"$release_dir/$target_files"

echo "Running ota_from_target_files"
ota_from_target_files \
	--block \
	-k "${key_dir}/releasekey" \
  	"${release_dir}/${target_files}" \
    "${release_dir}/${device}-ota_update-${build_number}.zip"

echo "Running img_from_target_files"
img_from_target_files \
	"${release_dir}/${target_files}" \
	"${release_dir}/${device}-img-${build_number}.zip"

echo "Running generate-factory-images"

cat <<-EOF | bash
	cd "$release_dir"
	source "${base_dir}/device/common/clear-factory-images-variables.sh"
	export BUILD="$build_number"
	export DEVICE="$device"
	export PRODUCT="$device"
	export VERSION="$version"
	# radio/bootloader not supported by generate-factory-images-common atm
	export BOOTLOADERSRC=boot.img
	export BOOTLOADER="$bootloader"
	export RADIO="$radio"
	source "${base_dir}/device/common/generate-factory-images-common.sh"
EOF
