#!/bin/bash
set -e; eval "$(environment)"

base_dir="${BASE_DIR?}"
cores=$(nproc)

cd "${base_dir}"
export ALLOW_MISSING_DEPENDENCIES=true

command -v avbtool || make -j"$cores" avbtool
command -v generate_verity_key || make -j"$cores" generate_verity_key
command -v dtc || make -j"$cores" dtc
command -v mkdtimg || make -j"$cores" mkdtimg
command -v fastboot || make -j"$cores" fastboot
